#ifndef GLOBALVARIABLES_H
#define GLOBALVARIABLES_H

#define ERROR_LOADING_FILE 0
#define ERROR_JSON_LOADING 1
#define ERROR_JSON_CONVERSION 2
#define ERROR_JSON_CONVERSION_ARRAY 3
#define ERROR_JSON_CONVERSION_GATE 4
#define ERROR_JSON_CONVERSION_PIN 5
#define ERROR_JSON_CONVERSION_ID 7
#define ERROR_JSON_CONVERSION_LEVEL 8
#define ERROR_JSON_CONVERSION_LABEL 9
#define ERROR_JSON_CONVERSION_CONNECTED 10
#define ERROR_READING_FILE 11


#endif // GLOBALVARIABLES_H
